In [1]:
import numpy as np

In [2]:
# print the one by method
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
# print zeros by using method
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
# print counting
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
# print the even numbers
for a in np.arange(2,14,2):
    print(a)

2
4
6
8
10
12


In [7]:
# print the odd numbers
for i in np.arange(1,14,2):
    print(i)

1
3
5
7
9
11
13


In [9]:
# print the 2nd element equal to 1st element
np.full(5,7)

array([7, 7, 7, 7, 7])

In [14]:
# print unintialized values
np.empty(16)

array([4.67296746e-307, 1.69121096e-306, 7.56599128e-307, 1.78014736e-306,
       1.86921551e-306, 1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
       1.11260619e-306, 8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
       1.37962456e-306, 1.69111861e-306, 1.78020169e-306, 7.56605918e-307])

In [17]:
# create an evenly spaced array from start to end
array = np.linspace(2,3,6)
print(array)

[2.  2.2 2.4 2.6 2.8 3. ]


In [18]:
# Create an identity matrix of arrar
array = np.eye(4)
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
# random values between 0 and 1
array = np.random.rand(5)
print(array)

[0.14418538 0.34770778 0.94705424 0.48797549 0.9022987 ]


In [21]:
# random integers between o and 9
array = np.random.randint(0,10,10)
print(array)

[1 2 9 6 0 8 9 3 9 7]


In [23]:
# np.zeros_like: Creates an array of zeros with the same shape and type as a given array.
base_arr = np.array([1,2,3,4])
print(base_arr)
array = np.zeros_like(base_arr)
print(array)

[1 2 3 4]
[0 0 0 0]


In [25]:
# np.ones_like: Creates an array of ones with the same shape and type as a given array.
base_arr = np.array([1,2,4,5,6])
print(base_arr)
array = np.ones_like(base_arr)
print(array)

[1 2 4 5 6]
[1 1 1 1 1]


In [27]:
# np.full_like: Creates an array with the same shape and type as a given array, filled with a specified value.

base_arr = np.array([2,4,5,7,8])
print(base_arr)
array = np.full_like(base_arr,9)
print(array)

[2 4 5 7 8]
[9 9 9 9 9]


In [29]:
# create a diagonal array
array  = np.diag([4,6,7,3,5])
print(array)

[[4 0 0 0 0]
 [0 6 0 0 0]
 [0 0 7 0 0]
 [0 0 0 3 0]
 [0 0 0 0 5]]


In [34]:
# create a lower triangular array
array = np.tri(4,4)
print(array)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [40]:
# np.mgrid: Creates a dense multi-dimensional “meshgrid”
x,y = np.mgrid[0:5,0:3]
print(x)
print(y)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


In [44]:
# np.ogrid: Creates an open multi-dimensional “meshgrid”.
x,y = np.ogrid[0:4,0:5]
print(x)
print(y)

[[0]
 [1]
 [2]
 [3]]
[[0 1 2 3 4]]


In [52]:
string = '1 2 3 4 5'
print(string)
array = np.fromstring(string,dtype=int,sep=' ')
print(array)

1 2 3 4 5
[1 2 3 4 5]


In [ ]:
import numpy as np

# Initial tuple of strings
string_tuple = ('1', '2', '3', '4', '5')
# Join the tuple into a single string with spaces
string = ' '.join(string_tuple)
print(string)  # Output: 1 2 3 4 5

# Convert the string to a NumPy array
array = np.fromstring(string, dtype=int, sep=' ')
print(array)  # Output: [1 2 3 4 5]


In [58]:
string_tuple = '1', '2', '3', '4', '5'
string = ' '.join(string_tuple)
print(string)

array = np.fromstring(string,dtype=float,sep = ' ')
print(array)

1 2 3 4 5
[1. 2. 3. 4. 5.]
