## Q1:
#### Convert 1D array into 2D array with two rows?

In [1]:
import numpy as np

In [6]:
array = np.arange(0,10)
print(array)
array.reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Q2:
### How to stack two arrays vertically?

In [8]:
array1 = np.arange(10)
array2 = array1.reshape(2,5)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [10]:
array3 = np.arange(10,dtype=int)
array4 = array3.reshape(2,5)
array4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
stacked_array = np.vstack((array2,array4))
print(stacked_array)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]


## Q3:
### How to stack two arrays horizontally?

In [13]:
array1 = np.arange(10)
array2 = array1.reshape(2,5)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
array3 = np.arange(10,dtype=int)
array4 = array3.reshape(2,5)
array4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
stacked_array = np.hstack((array2,array4))
print(stacked_array)

[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]
